language: csharp
solution: CertDump.sln

dist: xenial
mono: none
dotnet: 2.2
script:
    - dotnet publish -c Release -r win-x64
    - dotnet publish -c Release -r linux-x64
    - zip -r certdump-win-x64.zip ./CertDump/bin/Release/netcoreapp2.2/win-x64/publish/
    - zip -r certdump-linux-x64.zip ./CertDump/bin/Release/netcoreapp2.2/linux-x64/publish/
