language: csharp
solution: CertDump.sln

dist: xenial
mono: none
dotnet: 2.2
script:
- dotnet publish -c Release -r win-x64
- cp -r ./CertDump/bin/Release/netcoreapp2.2/win-x64/publish/ ./certdump-win-x64
- zip -r certdump-win-x64.zip ./certdump-win-x64
- dotnet publish -c Release -r linux-x64
- cp -r ./CertDump/bin/Release/netcoreapp2.2/linux-x64/publish/ ./certdump-linux-x64
- zip -r certdump-linux-x64.zip ./certdump-linux-x64

deploy:
  provider: releases
  api_key:
    secure: MLiEU430BdTWSlSh7dZdMkGPrPlTJk/rE4vNwEL/dXXQQHfiShU6W0r4e7iTo83zTw55jhXPn2akvnd7dDe6W+dCAuG7/jKD3xNGdKa0PZqpknVm+U5ahxXzYDNRHPg+QMiY2F0dyjWwaAiGTHxwUlmA1TRRsAl3fpL+CuenX1NxgmacQ2rf2HMJH/oSFxmshf2ULAxVlPH8KNesQMPVYuY0yQKFXIFnoTSrFZjgpxEZTUkbpHui5ppGfsmWXy5JEthd+xXSs7w0Q1gC6lt6zCMV/E9gNyvHlOm+PCkCLOwSXa4KilUhjK6X5VhWGTTZl6ndHezWFxxxWo2f7SsPponWDqs55T3z1+NB7+N33louPU/alrR5W4PKzSYcf+6ke/QejpLMZHgMvkLR39ntp2XvH8I/xBYLt/TU2IKlwKJuYU5nnZfoasBS7BFEZIpNZ0tdLkNyHbSqryjFA3gokDby9f1FdgFHbiiGBxZwfGfXw/CAz6mRyGuwAGTmSfSfUMS3F7586lQ++C1qiAWpZqwO96X5byswMy3nqrVTflkTcVnwjLDik9drKthfXNx7FNHggc45uzRABcDtvh++WonPP5+kOoJf7lgeZ2QlgznqUmEC8AlAvhvnreyF5h1D4F9y23gnda+hrioQsvNSlKrlfNhDr1M6EBC5dIAUXs0=
  file: 
    - "certdump-win-x64.zip"
    - "certdump-linux-x64.zip"
  on:
    repo: secana/CertDump
    tags: true
