# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master
- features/*

pool:
  vmImage: 'windows-2019'

variables:
  buildConfiguration: 'Release'

steps:

- powershell:  dotnet publish -r win-x64 -c release 
  displayName: Build native Windows executable

- powershell: cp .\CertDump\bin\Release\netcoreapp2.1\win-x64\native\CertDump.exe $(Build.ArtifactStagingDirectory)
  displayName: Copy CertDump.exe to "Artifacts Staging Directory"

- task: GitHubRelease@0
  diplsyName: Create GitHub Release
  inputs:
    gitHubConnection: 'CertDump'
    repositoryName: 'secana/CertDump'
    tagSource: manual
    tag: $(Build.BuildNumber)
    assets: $(Build.ArtifactStagingDirectory)/*.exe