# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master
- features/*

pool:
  vmImage: 'windows-2019'

variables:
  buildConfiguration: 'Release'

steps:

- task: PowerShell@2
  displayName: Install .Net Core 3.0 preview
  inputs:
    targetType: filePath
    failOnStderr: true
    filePath: .\dotnet-install.ps1
    arguments: "-Channel release/3.0.0-preview3"

- powershell:  dotnet publish -r win-x64 -c release 
  displayName: Build native Windows executable
